# -*- coding: utf-8 -*-
"""Week1_Day5_Challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1374wo96eYMZ30WNBXa9HNFnhMoj8Y6

Apolo BARNABAS
Week1_Day5_Challenge
"""

#Ask the user to enter a word.
word = input("Enter a word: ")

letter_dict = {}

for char in word:
    if char in letter_dict:
        print(f"{char} is already a key")
    else:
        print(f"{char} is NOT a key yet")

#2. Creating the Dictionary:
word = input("Enter a word: ")
char_dict = {}

for index, char in enumerate(word):
    if char in char_dict:
        char_dict[char].append(index)  # add index if key exists
    else:
        char_dict[char] = [index]      # create new key with list

print(char_dict)

#Ensure that the characters (keys) are strings.
#Ensure that the indices (values) are stored in lists.

word = input("enter a word: ")
char_dict = {}

for index, char in enumerate(word):
    key = str(char)

    if key in char_dict:
        char_dict[key].append(index)
    else:
        char_dict[key] = [index]

print(char_dict)

"""Challenge 2: Affordable Items"""

# Store Data:
items_purchase = {
    "Water": "$1",
    "Bread": "$3",
    "TV": "$100",
    "Fertilizer": "$20"
}
print(items_purchase)

#Store Data :
wallet = int(input("Enter the amount of money you have: "))
purchased_items = []

for item, price in items_purchase.items():
    price_value = int(price.replace("$", ""))  # convert "$20" → 20

    if wallet >= price_value:
        wallet -= price_value
        purchased_items.append(item)

if purchased_items:
    print("Items you can buy:", purchased_items)
else:
    print("Nothing")

#You will also be given a string (wallet) representing the amount of money you have.

def affordable_items(items_purchase, wallet):
    # Convert wallet to integer
    money = int(wallet.replace("$", ""))

    affordable = []

    for item, price in items_purchase.items():
        # Convert price to integer
        cost = int(price.replace("$", ""))

        if cost <= money:
            affordable.append(item)

    if not affordable:
        return "Nothing"

    return sorted(affordable)

items_purchase = {
    "Water": "$1",
    "Bread": "$3",
    "TV": "$1000"
}

wallet = "$4"

print(affordable_items(items_purchase, wallet))

#Data Cleaning:

def affordable_items(items_purchase, wallet):
    # Remove $ and commas from wallet
    money = int(wallet.replace("$", "").replace(",", ""))

    affordable = []

    for item, price in items_purchase.items():
        # Clean price string the same way
        cost = int(price.replace("$", "").replace(",", ""))

        if cost <= money:
            affordable.append(item)

    if not affordable:
        return "Nothing"

    return sorted(affordable)

print(affordable_items(items_purchase, wallet))

def affordable_items(items_purchase, wallet):
    # Remove $ and commas from wallet
    money = int(wallet.replace("$", "").replace(",", ""))

    affordable = []

    for item, price in items_purchase.items():
        # Clean price string the same way, removing both $ and commas
        cost = int(price.replace("$", "").replace(",", ""))

        if cost <= money:
            affordable.append(item)

    if not affordable:
        return "Nothing"

    return sorted(affordable)

items_purchase = {
    "Water": "$1",
    "Bread": "$3",
    "TV": "$1,000",
    "Phone": "$500"
}

wallet = "$504"

print(affordable_items(items_purchase, wallet))

#If the basket is empty (no items can be afforded), return the string “Nothing”.
def affordable_items(items_purchase, wallet):
    # Clean wallet
    money = int(wallet.replace("$", "").replace(",", ""))

    basket = []

    for item, price in items_purchase.items():
        # Clean price
        cost = int(price.replace("$", "").replace(",", ""))

        if cost <= money:
            basket.append(item)
            money -= cost  # update wallet

    # ✅ Check if basket is empty
    if not basket:
        return "Nothing"

    return basket
    items_purchase = {
    "Phone": "$500",
    "Laptop": "$1,000"
}

wallet = "$100"
print(affordable_items(items_purchase, wallet))

def affordable_items(items_purchase, wallet):
    # Clean wallet
    money = int(wallet.replace("$", "").replace(",", ""))

    basket = []

    for item, price in items_purchase.items():
        # Clean price
        cost = int(price.replace("$", "").replace(",", ""))

        if cost <= money:
            basket.append(item)
            money -= cost  # update wallet

    # If empty
    if not basket:
        return "Nothing"

    # Return sorted basket
    return sorted(basket)

items_purchase = {
    "Water": "$1",
    "Bread": "$3",
    "Apple": "$2"
}

wallet = "$6"

print(affordable_items(items_purchase, wallet))

#4 Given:
items_purchase = {
    "Water": "$1",
    "Bread": "$3",
    "TV": "$100",
    "Fertilizer": "$20"
}
wallet = "$300"
print(items_purchase)

#Step-by-step:
#Wallet = $300
#Items in order:
#Water ($1) → buy → money = 299
#Bread ($3) → buy → money = 296
#TV ($1,000) → too expensive ❌
#Fertilizer ($20) → buy → money = 276

items_purchase = {
    "water","bread","fertilizer"
}
print(items_purchase)

items_purchase = [
    'Apple', 'Bananas', 'Fan', 'Honey', 'Spoon'
]
print(items_purchase)

# Output: Nothing
# Remaining wallet: $1
items_purchase3 = {"Phone": "$999", "Speakers": "$300", "Laptop": "$5,000", "PC": "$1,200"}
wallet3 = "$1"
affordable_items(items_purchase3, wallet3)